### ISSUE TITLE
Quick question..

### ISSUE THREAD

**Issue by firewood-gatherer75** [trgkanki/basic2cloze#1] opened 2020-04-15 07:31 UTC
Hi!

I was just wondering if there is a way of modifying this add on so that it doesn’t automatically change the note type of the next card to cloze, but only those cards that have cloze deletion in them?

Thanks!

**Comment by phu54321** [comment] 2020-04-15 13:59
Will look at 04/19

Before that, could you clarify the question a bit more? I don't actually understand your question. 

> it doesn’t automatically change the note type of the next card to cloze,

What does this 'next' mean? This addon interferes with the current card only, not afterwards. Could you please state a reproduction steps for your questions?

**Comment by phu54321** [comment] 2020-05-04 01:30
Closing due to lack of information

**Closed as completed by phu54321** 2020-05-04 01:30 UTC
